name: Simple Action
on: [push]

jobs: 
  simple-action:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@main
              # actions/hello-world-javascript-action@v1.1.3
              # actions/hello-world-javascript-action@Commit ID
        with:
          who-to-greet: Angelos
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"